//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMarketClient.LiveStockData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LiveStockData.ILiveStockDataSvc")]
    public interface ILiveStockDataSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiveStockDataSvc/GetLiveStockDetails", ReplyAction="http://tempuri.org/ILiveStockDataSvc/GetLiveStockDetailsResponse")]
        DataLayer.Entities.Stock[] GetLiveStockDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiveStockDataSvc/GetLiveStockDetails", ReplyAction="http://tempuri.org/ILiveStockDataSvc/GetLiveStockDetailsResponse")]
        System.Threading.Tasks.Task<DataLayer.Entities.Stock[]> GetLiveStockDetailsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILiveStockDataSvcChannel : StockMarketClient.LiveStockData.ILiveStockDataSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LiveStockDataSvcClient : System.ServiceModel.ClientBase<StockMarketClient.LiveStockData.ILiveStockDataSvc>, StockMarketClient.LiveStockData.ILiveStockDataSvc {
        
        public LiveStockDataSvcClient() {
        }
        
        public LiveStockDataSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LiveStockDataSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiveStockDataSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiveStockDataSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataLayer.Entities.Stock[] GetLiveStockDetails() {
            return base.Channel.GetLiveStockDetails();
        }
        
        public System.Threading.Tasks.Task<DataLayer.Entities.Stock[]> GetLiveStockDetailsAsync() {
            return base.Channel.GetLiveStockDetailsAsync();
        }
    }
}
